# -*- coding: utf-8 -*-
"""Check_Temperature

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AdNLTmupTRknJ30kszmk-NPnsRBLz5zY
"""

#Christopher Kenny
#CS-175

#Checking Temp Utilizing While Loop Within Function:
def check_temp():
    max_temp = 100
    temp = int(input("Enter the current temperature (in °F): "))
    while temp > max_temp:
        print("The temperature is too high.")
        temp = int(input("Please enter the re-adjusted temperature: "))
    else:
      print("The temperature is acceptable.")
#Print
check_temp()